### ISSUE TITLE
Fail to compile on Linux

### ISSUE THREAD

**Issue by tan-wei** [nelsonjchen/speedtest-rs#39]
Version:
  - rustc 1.43.0-nightly (0eb878d2a 2020-02-28)
  - cargo 1.43.0-nightly (e57bd0299 2020-02-21)

Error message:
```console
   Compiling mockito v0.21.0
error[E0432]: unresolved imports `assert_json_diff::Comparison`, `assert_json_diff::Actual`, `assert_json_diff::Expected`
   --> /home/winterreise/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.21.0/src/lib.rs:527:24
    |
527 | use assert_json_diff::{Comparison, assert_json_no_panic, Actual, Expected};
    |                        ^^^^^^^^^^                        ^^^^^^  ^^^^^^^^ no `Expected` in the root
    |                        |                                 |
    |                        |                                 no `Actual` in the root
    |                        no `Comparison` in the root

error[E0603]: function `assert_json_no_panic` is private
   --> /home/winterreise/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.21.0/src/lib.rs:527:36
    |
527 | use assert_json_diff::{Comparison, assert_json_no_panic, Actual, Expected};
    |                                    ^^^^^^^^^^^^^^^^^^^^ this function is private
    |
note: the function `assert_json_no_panic` is defined here
   --> /home/winterreise/.cargo/registry/src/github.com-1ecc6299db9ec823/assert-json-diff-1.0.3/src/lib.rs:241:1
    |
241 | fn assert_json_no_panic(lhs: &Value, rhs: &Value, mode: Mode) -> Result<(), String> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0603.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `mockito`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `speedtest-rs v0.0.13`, intermediate artifacts can be found at `/tmp/cargo-installPWs4Qm`

Caused by:
  build failed
```

**Comment by nelsonjchen** [comment]
Interesting timing. I got the CI system going and the most recent nightly
didn't explode. 🤔

**Comment by tan-wei** [comment]
Maybe I should retry it later, because nightly is not that stable.

**Comment by tan-wei** [comment]
This time, I'v tried to install it with stable and nightly. However, it just complains the same error. I check the compilation message in CI system. I find the version of `mockito` is different:
  - In CI system, the version of `mockito` is v0.23.3
  - In my Manjaro, with `cargo install speedtest-rs`, the version of `mockito` is v0.21.0

Why the different versions are shown here? Feel confused.

**Comment by nelsonjchen** [comment]
It might be because I haven't released a new version to crates.io. That should probably solve it. I'll do that when I am able to.

**Comment by nelsonjchen** [comment]
In other words, I guess maybe the version on crates.io is using a version of `mockito` that isn't compatible with nightly.

**Comment by tan-wei** [comment]
I also tried it with stable, it is the same result. Maybe a release will work.

**Comment by nelsonjchen** [comment]
I pushed a new version to crates.io . Could you give it a try?

**Comment by polyzen** [comment]
Both versions have built fine for me with the `--locked` option and stable toolchain on Arch Linux.

**Comment by tan-wei** [comment]
@polyzen Thanks! But I prefer use `cargo install` when I use such rust crate. And now, the fresh release is built sucessfully.

**Comment by tan-wei** [comment]
@nelsonjchen I confirm that the issue should be closed now because the new release is fine for me. Thanks very much.
