### ISSUE TITLE
Consistently getting about half the upload speed compared to other speedtests

### ISSUE THREAD

**Issue by polyzen** [nelsonjchen/speedtest-rs#41]
speedtest-rs: https://www.speedtest.net/result/9104622437.png
https://github.com/sivel/speedtest-cli against the same server: https://www.speedtest.net/result/9104623103.png

https://www.verizon.com/speedtest/ and https://fast.com/ also show >=300 Mbps up.

Edit: speedtest-rs 0.0.13 and 0.0.14 on Arch Linux

**Comment by nelsonjchen** [comment]
The logic has changed quite a lot since 2015. For instance, speedtest-cli looks to be configuring themselves from speedtest's config. This will take some time to get it back onto how 2020 speedtest-cli does it.

**Comment by nelsonjchen** [comment]
Woah, I didn't realize this but in 2019 Ookla released an official CLI and native version of the tool. It can be run on quite a few platforms.

https://www.speedtest.net/apps/cli

It's not FOSS though. No source is available.

I'll still try to match what speedtest-cli is doing but if you're in need of a native CLI that's accurate, I suggest taking a look there.

**Comment by polyzen** [comment]
On 0.0.15 the upload shows about 25 Mbps.

**Comment by nelsonjchen** [comment]
Addressed in #74
