### ISSUE TITLE
Possibly upstream issue with --list option.

### ISSUE THREAD

**Issue by thaewrapt** [nelsonjchen/speedtest-rs#49]
About a week ago the list returned by this client (and some others as well) became constantly truncated for about 1100-1200km radius from location of issuer instead of worldwide as before. Thanks to a detailed documentation you provide, I can see it's truncated already at https://www.speedtest.net/speedtest-servers-static.php (for me it's now not further than Poland's servers, all those other servers are still available through web interface of speedtest.net via "change server" feature).

**Comment by thaewrapt** [comment]
https://github.com/sivel/speedtest-cli/issues/717 same issue reported elsewhere.

**Comment by nelsonjchen** [comment]
My response would pretty much be the same as upstream: https://github.com/sivel/speedtest-cli/issues/717#issuecomment-609831565

**Comment by hendranata** [comment]
i have change another internet provider.. the result --list are same.. cant test the server that located far away from us.. 
any solution?
