### ISSUE TITLE
Can't use crate as library

### ISSUE THREAD

**Issue by ollien** [nelsonjchen/speedtest-rs#76]
I wanted to use this project as a library in a project of mine, but because there's no `lib.rs`, it seems that I can't actually use this crate without vendoring the source code in my project.

```
$ cargo build
   Compiling my-project v0.1.0 (/home/nick/Documents/code/my-project)
error[E0432]: unresolved import `speedtest_rs`
 --> src/main.rs:1:5
  |
1 | use speedtest_rs::*;
  |     ^^^^^^^^^^^^ use of undeclared type or module `speedtest_rs`
```

Would you consider adding a `lib.rs`? I saw in another issue you don't want to commit to a specific API at the moment, but I'd love to be able to use this code as a dependency, rather than just vendored source.

**Comment by nelsonjchen** [comment]
I'll add one, but with no guarantees on API stability.

**Comment by ollien** [comment]
Thank you!
