### ISSUE TITLE
Rename crate from 'speedtest-rs' to 'speedtest'

### ISSUE THREAD

**Issue by dtolnay** [nelsonjchen/speedtest-rs#8]
Every crate on crates.io is for Rust :smile: no reason for the -rs suffix.

**Comment by nelsonjchen** [comment]
It's a little late to do that at this point. Unfortunately, this was already published.

I greatly prefer to minimize confusion by keeping things to just a single crate and name. I've seen other projects publish a new crate under a new name sans prefix or suffix or whatever. I **really** don't want two speedtest{-rs} crates showing up on crates.io.

I'll be sure to not use such a suffix on any future or new crates in the future though. Perhaps someone should suggest a "lint" in `cargo publish` on this to prevent this, going forward.
